import type { Pathway } from "@/types/pathway";
import type { ContentItem } from "@/types/content";
import type { Metadata } from "next";

export const educatorPathways:Pathway[]=[
 {id:"elementary-classroom",slug:"elementary-classroom",title:"Elementary Classroom",shortTitle:"Elementary Classroom",gradeLabel:"PreK–5",summary:"Plan connected, age-appropriate learning across a busy elementary day while keeping young learners’ privacy and teacher supervision central.",subjects:["elementary"],gradeBands:["prek-2","3-5"],roles:["classroom-teacher","special-education","instructional-support"],interests:["lesson-planning","differentiation","family-communication","assessment","accessibility"],usefulFrame:"Ask for options that fit your learning target, developmental level, routines, time, and materials. Adults should review and mediate AI-generated content for young children.",promptWorkflow:"lesson-planning",promptLabel:"Plan an elementary lesson",useCases:[
  {title:"Design centers and stations",description:"Draft complementary station purposes, directions, rotations, and quick checks without turning every center into independent screen time.",example:"Create four 12-minute centers for practicing place-value representations with base-ten blocks, cards, and teacher conferencing."},
  {title:"Differentiate access",description:"Vary explanations, materials, grouping, and response modes while preserving the same essential learning target.",example:"Offer concrete, visual, oral, and written entry points to a shared science observation."},
  {title:"Support vocabulary",description:"Generate child-friendly explanations, examples, gestures, picture ideas, and repeated-use opportunities.",example:"Build a vocabulary routine for habitat, shelter, survive, and adapt."},
  {title:"Strengthen questioning",description:"Develop open and closed questions for read-alouds, number talks, investigations, and formative checks.",example:"Sequence questions that move from noticing to explaining during a pattern-block task."},
  {title:"Vary lessons and activities",description:"Brainstorm a fresh route to a familiar target when energy, time, space, or materials change.",example:"Adapt a planned outdoor measurement activity for a rainy day without losing hands-on comparison."},
  {title:"Draft family communication",description:"Create a plain-language starting point that a teacher can personalize and check for tone, translation needs, and school policy.",example:"Explain an upcoming inquiry unit and suggest low-cost ways families can notice patterns at home."},
  {title:"Build formative checks",description:"Generate quick, observable ways for children to show understanding through talk, drawing, movement, sorting, or writing.",example:"Create three exit choices for identifying a story’s setting and key events."},
  {title:"Make explanations accessible",description:"Reframe an idea with concrete examples and reduced language load without removing its intellectual substance.",example:"Explain equal groups using classroom materials before introducing multiplication notation."},
 ],considerations:[{title:"Supervision matters",body:"For younger learners, educator-led use is generally safer and more instructionally useful than sending children to interact with a public AI system on their own."},{title:"Connected planning",body:"Elementary work crosses subjects. AI can help map connections, but the teacher decides whether the sequence is coherent, age-appropriate, and realistic."}],cautions:["Do not recommend unsupervised use of public AI systems by young children.","Never enter student names, records, reading levels tied to individuals, or family details.","Check examples for developmental appropriateness, accuracy, stereotypes, and unnecessary complexity.","Follow local requirements for approved tools, accounts, and family communication."]},
 {id:"visual-arts",slug:"visual-arts",title:"Visual Arts",shortTitle:"Visual Arts",gradeLabel:"K–12",summary:"Use AI to support artistic inquiry, critique, research, and lesson design while examining authorship, ownership, process, and generative imagery with care.",subjects:["visual-arts"],gradeBands:["prek-2","3-5","6-8","9-12"],roles:["specialist","classroom-teacher","instructional-support"],interests:["lesson-planning","differentiation","feedback","ai-literacy","assignment-redesign"],usefulFrame:"Start with the artistic thinking students should demonstrate. Treat generated imagery as a subject for inquiry or one possible material—not as an automatic substitute for making, observation, revision, or original decision-making.",promptWorkflow:"activity-brainstorming",promptLabel:"Brainstorm an art activity",useCases:[
  {title:"Develop critique questions",description:"Draft observation-first questions about composition, material choices, meaning, context, and revision.",example:"Create critique prompts for a middle-school mixed-media work without assuming the artist’s intention."},
  {title:"Explore composition and concept",description:"Generate constraints, visual problems, or conceptual provocations that leave room for divergent student decisions.",example:"Design three composition challenges using scale, repetition, and negative space."},
  {title:"Differentiate vocabulary",description:"Explain formal and contextual terms through examples, comparisons, and accessible language.",example:"Contrast value, contrast, emphasis, and focal point at two reading levels."},
  {title:"Scaffold artist research",description:"Organize inquiry questions, source-checking steps, and context categories without inventing facts or citations.",example:"Build a research organizer connecting an artist’s materials, place, historical context, and choices."},
  {title:"Support artist statements",description:"Develop reflection questions that help students articulate decisions without writing the statement for them.",example:"Ask a sequence of questions about process, revision, meaning, and audience."},
  {title:"Ideate lessons",description:"Brainstorm material-conscious lessons connected to a standard, big idea, collection, or local context.",example:"Develop printmaking explorations about repetition and community using classroom-safe materials."},
  {title:"Examine generative imagery",description:"Compare how prompts, training data, selection, editing, and presentation complicate authorship and ownership.",example:"Analyze several creation processes and debate what counts as artistic decision-making in each."},
  {title:"Evaluate process and product",description:"Create reflection or assessment approaches that make experimentation, revision, craft, and intention visible.",example:"Draft a process journal structure for documenting discarded ideas and turning points."},
 ],considerations:[{title:"Neutral, critical examination",body:"AI image generation is neither inherently beneficial nor inherently harmful in art education. Its value depends on the learning goal, age, process, sources, classroom context, and how authorship and labor are discussed."},{title:"Copyright and ownership",body:"Copyright status, licenses, training-data practices, and local policy can differ. Avoid presenting generated output as legally risk-free or automatically ownable."}],cautions:["Do not upload student artwork or identifiable images without permission and an approved system.","Verify artist biographies, cultural context, quotations, and image rights with reliable sources.","Do not let generated images erase the process evidence an assignment is meant to assess.","Name uncertainty around copyright, attribution, authorship, and artistic ownership."]},
 {id:"music",slug:"music",title:"Music",shortTitle:"Music",gradeLabel:"K–12 · General music, band, choir, orchestra",summary:"Support rehearsal, listening, theory, reflection, context, and composition across ensemble and general music settings without replacing musicianship students need to demonstrate.",subjects:["music"],gradeBands:["prek-2","3-5","6-8","9-12"],roles:["specialist","classroom-teacher","instructional-support"],interests:["lesson-planning","differentiation","feedback","assessment","ai-literacy"],usefulFrame:"Provide ensemble type, experience range, musical objective, rehearsal time, score or excerpt context you are permitted to share, and constraints. Verify musical details against the score, recording, edition, and your own ear.",promptWorkflow:"lesson-planning",promptLabel:"Plan a music lesson or rehearsal",useCases:[
  {title:"Plan rehearsals",description:"Sequence warm-ups, focused excerpts, listening goals, section work, and run-throughs around a specific musical priority.",example:"Plan a 45-minute band rehearsal emphasizing balance and release consistency in two known passages."},
  {title:"Explain music theory",description:"Generate alternate explanations, analogies, aural examples, and graduated practice for a theory concept.",example:"Explain tonic and dominant function for general music, beginning band, and high-school theory."},
  {title:"Prompt practice reflection",description:"Help students notice strategies, evidence of change, and their next focused step rather than report minutes alone.",example:"Create a two-minute reflection after practicing a difficult shift or vowel transition."},
  {title:"Build repertoire context",description:"Organize research questions about composer, arranger, culture, form, function, and performance practice.",example:"Create a source-checking guide for the historical and cultural context of an ensemble selection."},
  {title:"Draft program notes",description:"Create a fact-checkable starting structure that students or directors revise for audience, voice, and accuracy.",example:"Outline concise notes connecting form, context, and a listening cue without invented quotations."},
  {title:"Differentiate practice",description:"Offer options for tempo, chunking, fingering or sticking focus, audiation, modeling, and peer rehearsal.",example:"Develop practice routes for an eight-measure passage at three readiness points."},
  {title:"Support pronunciation and translation",description:"Generate provisional pronunciation breakdowns or translation comparisons that are checked against authoritative language and diction sources.",example:"Compare literal and singable meanings of a choral phrase and flag uncertain pronunciation."},
  {title:"Explore composition and authorship",description:"Develop constraints and reflection questions that distinguish tool assistance from musical decisions students must make.",example:"Design a motif-development task where students document what they generated, selected, revised, and performed."},
 ],considerations:[{title:"Many music classrooms",body:"General music, band, choir, and orchestra share some planning needs, but rehearsal pacing, notation, technique, voicing, instrumentation, and assessment evidence differ."},{title:"Authorship implications",body:"When AI contributes musical material, clarify which compositional, interpretive, and performance decisions students are expected to demonstrate and disclose."}],cautions:["Verify pitches, ranges, fingerings, transpositions, translations, pronunciation, and historical claims.","Do not upload copyrighted scores, recordings, or student performances to an unapproved system.","Protect student voice recordings and performance identities.","Do not let generated material replace the listening, creating, reading, or performing the objective requires."]},
 {id:"world-languages",slug:"world-languages",title:"World Languages",shortTitle:"World Languages",gradeLabel:"K–12",summary:"Create contextualized language practice while keeping proficiency goals, cultural accuracy, authentic production, and the limits of translation tools visible.",subjects:["world-languages"],gradeBands:["prek-2","3-5","6-8","9-12"],roles:["specialist","classroom-teacher","instructional-support"],interests:["lesson-planning","differentiation","feedback","ai-literacy","assignment-redesign"],usefulFrame:"Name the target language, proficiency range, communicative mode, language function, cultural context, and what students must produce independently. Ask for comprehensible language, then review it for naturalness and regional fit.",promptWorkflow:"activity-brainstorming",promptLabel:"Build a language-practice scenario",useCases:[
  {title:"Create conversational scenarios",description:"Generate plausible interpersonal situations with roles, information gaps, purposes, and optional complications.",example:"Design an intermediate-low scenario for making plans when two friends have different schedules."},
  {title:"Vary by proficiency",description:"Adjust language functions, text complexity, scaffolds, and expected output—not merely the number of words.",example:"Create novice-mid and intermediate-low versions of asking for and giving directions."},
  {title:"Reinforce vocabulary",description:"Place vocabulary in meaningful chunks, semantic groups, circumlocution practice, and retrieval activities.",example:"Develop a classroom routine for using food vocabulary to express preferences and ask follow-up questions."},
  {title:"Adapt reading",description:"Create a provisional, level-conscious adaptation while preserving key cultural meaning and comparing it with the authentic source.",example:"Reduce syntactic density in a public-domain text and identify what nuance was lost."},
  {title:"Build cultural-context activities",description:"Generate inquiry questions and comparison tasks that avoid presenting a culture as a single fixed set of facts.",example:"Explore how greetings vary by relationship, setting, region, and generation using verified examples."},
  {title:"Develop feedback",description:"Draft feedback aligned to a proficiency target and a small number of high-leverage language features.",example:"Respond to an anonymous writing sample by separating comprehensibility, task completion, and recurring form issues."},
  {title:"Examine translation tools",description:"Compare literal, contextual, and machine translations and discuss what each reveals or obscures.",example:"Analyze three translations of an idiom and justify which fits a specific situation."},
  {title:"Protect authentic production",description:"Redesign tasks so students still demonstrate spontaneous speaking, interpretive choices, or independent writing.",example:"Pair AI-supported rehearsal with an in-class conversation and short disclosure note."},
 ],considerations:[{title:"Practice versus replacement",body:"AI may support rehearsal, feedback, vocabulary retrieval, or scenario generation. It bypasses learning when it performs the language production, interpretation, or interaction students are supposed to demonstrate."},{title:"Language has context",body:"Outputs may be grammatically plausible yet unnatural, regionally mismatched, overly formal, culturally reductive, or insensitive. Fluent is not the same as appropriate."}],cautions:["Do not enter identifiable student writing, recordings, or performance data into unapproved systems.","Verify cultural claims and avoid treating communities or language varieties as monolithic.","Check translations, register, idioms, accents, and regional usage with authoritative sources.","State clearly which portions students must produce without AI assistance."]},
 {id:"secondary-core",slug:"secondary-core",title:"Secondary Core",shortTitle:"Secondary Core",gradeLabel:"Grades 6–12 · ELA, Math, Science, Social Studies",summary:"Use adaptable planning and assessment structures while respecting the distinct evidence, practices, and misconceptions of each core discipline.",subjects:["ela","mathematics","science","social-studies"],gradeBands:["6-8","9-12"],roles:["classroom-teacher","special-education","instructional-support"],interests:["lesson-planning","differentiation","assessment","feedback","assignment-redesign","academic-integrity"],usefulFrame:"Name the discipline, exact learning target, source material or data students may use, likely misconceptions, and the evidence of thinking the assignment should reveal.",promptWorkflow:"assignment-redesign",promptLabel:"Redesign an assignment",useCases:[
  {title:"Plan around disciplinary practice",description:"Sequence learning around what practitioners do: interpret text, model relationships, investigate phenomena, or reason with evidence.",example:"Contrast how evidence is used in a literary analysis, lab explanation, and historical argument."},
  {title:"Generate better questions",description:"Develop questions at varied levels while preserving the discipline’s way of knowing.",example:"Create ELA questions about author choices, math questions about structure, science questions about mechanisms, and history questions about sourcing."},
  {title:"Differentiate access",description:"Vary scaffolds, representations, source load, vocabulary support, and response routes without changing the essential claim, model, explanation, or reasoning target.",example:"Offer multiple ways into a common evidence-based explanation."},
  {title:"Create assessments",description:"Draft items and performance tasks aligned to the intended evidence, then check validity, ambiguity, accessibility, and answer quality.",example:"Build a short check that distinguishes procedural fluency from conceptual understanding in mathematics."},
  {title:"Focus feedback",description:"Generate criteria-aligned feedback structures that prioritize next steps over wholesale rewriting.",example:"Develop feedback prompts for claim-evidence reasoning in science without supplying the revised explanation."},
  {title:"Analyze misconceptions",description:"Brainstorm plausible incorrect ideas and diagnostic questions, then verify them against disciplinary expertise and student evidence.",example:"Compare misconceptions about equal signs, natural selection, source reliability, and narrative perspective."},
  {title:"Generate examples carefully",description:"Create examples, nonexamples, cases, data patterns, or source sets for teacher review.",example:"Generate candidate linear and nonlinear relationships, then check every value and representation."},
  {title:"Redesign for AI-era integrity",description:"Make process, reasoning, source use, discussion, revision, and in-class performance more visible.",example:"Turn a take-home response into staged source notes, a conference, a draft, and a reflective defense of choices."},
 ],considerations:[{title:"ELA",body:"Prioritize interpretation, textual evidence, rhetorical and authorial choices, voice, reading, and authentic composition—not generic answer production."},{title:"Mathematics",body:"Check calculations and notation. Distinguish procedural fluency, conceptual understanding, modeling, proof, and explanation."},{title:"Science",body:"Center evidence, models, mechanisms, uncertainty, investigation, safety, and the difference between observation and inference."},{title:"Social Studies",body:"Attend to sourcing, context, chronology, corroboration, perspective, contested interpretations, and the quality of evidence."}],cautions:["Verify every quotation, citation, calculation, data point, source, and historical or scientific claim.","Do not submit identifiable student work or records to an unapproved system.","AI detection scores are not proof of authorship or misconduct.","Keep the disciplinary thinking students are meant to demonstrate visible and assessable."]},
];

export function getPathway(slug:string){return educatorPathways.find(pathway=>pathway.slug===slug)}
export function buildPathwayMetadata(slug:string):Metadata{const pathway=getPathway(slug)!;const title=`${pathway.title} | K-12 AI Educator Resource`;return {title,description:pathway.summary,openGraph:{title,description:pathway.summary,images:[]},twitter:{title,description:pathway.summary,images:[]}}}

const allLevels=["starting","experimented","sometimes","regularly","leader"] as const;
export const pathwayContentItems:ContentItem[]=[
 ...educatorPathways.map(pathway=>({id:pathway.id,title:pathway.title,summary:pathway.summary,contentType:"learning" as const,gradeBands:pathway.gradeBands,subjects:pathway.subjects,roles:pathway.roles,interests:pathway.interests,aiLevels:[...allLevels],body:pathway.usefulFrame,reviewedDate:"2026-08-18"})),
 {id:"physical-education",title:"Physical Education",summary:"Authentic middle-school PE workflows grounded in movement objectives, access, equipment, and safety.",contentType:"learning",gradeBands:["6-8"],subjects:["physical-education"],roles:["specialist","classroom-teacher","instructional-support"],interests:["differentiation","lesson-planning","assessment","accessibility"],aiLevels:[...allLevels],body:"Use AI to expand planning options while preserving educator responsibility for physical and emotional safety.",reviewedDate:"2026-08-18"},
];
