import assert from "node:assert/strict"; import test from "node:test";
import { promptTemplates } from "../data/promptTemplates.ts"; import { generateWorkflowPrompt } from "../lib/promptGeneration.ts"; import { scoreContent } from "../lib/personalization.ts"; import { pathwayContentItems } from "../content/subjects/pathways.ts";
import { getProfilePromptDefaults, profileGradeLabel, profileSubjectLabel } from "../lib/profilePromptDefaults.ts";
import { getPromptFieldOptions } from "../lib/promptFieldOptions.ts";

test("all eight workflows generate complete deterministic prompts",()=>{assert.equal(promptTemplates.length,8);for(const template of promptTemplates){const prompt=generateWorkflowPrompt(template.id,template.defaults);assert.ok(prompt.length>400,`${template.id} prompt should be substantive`);assert.doesNotMatch(prompt,/undefined|null/i);assert.match(prompt,/Do not assume|Do not request|Do not assume details/i)}});

test("prompt forms never request prohibited student information",()=>{const labels=promptTemplates.flatMap(template=>template.fields.flatMap(field=>[field.label,field.hint])).join(" ");assert.doesNotMatch(labels,/student name|student id|identifiable grade|medical data|IEP document|504 document|disciplinary record/i);assert.match(labels,/without identifying|without names|Do not|identifiable student/i)});

test("personalization gives the strongest score to a matching pathway",()=>{const profile={role:"specialist",gradeBands:["6-8"],subjects:["music"],aiLevel:"starting",interests:["lesson-planning","assessment"],updatedAt:"2026-08-18T00:00:00.000Z"};const music=pathwayContentItems.find(item=>item.id==="music");const art=pathwayContentItems.find(item=>item.id==="visual-arts");assert.ok(music&&art);assert.ok(scoreContent(music,profile)>scoreContent(art,profile))});

test("Day 1 PE prompt wording remains intact",()=>{const template=promptTemplates[0];const prompt=generateWorkflowPrompt("differentiate-activity",template.defaults);assert.match(prompt,/preserving the primary learning objective rather than simply making the activity easier/);assert.match(prompt,/physical, medical, IEP, 504, legal, safety, or district-specific judgment|professional, medical, IEP, 504, legal, safety, or district-specific judgment/)});

test("select fields have usable options and valid defaults",()=>{for(const template of promptTemplates){for(const field of template.fields.filter(item=>item.control==="select")){assert.ok(field.options?.length,`${template.id}.${field.key} should provide options`);const defaultValue=template.defaults[field.key];if(defaultValue)assert.ok(field.options.includes(defaultValue),`${template.id}.${field.key} default should be an available option`)}}});

test("advanced fields are optional and every workflow keeps a short core",()=>{for(const template of promptTemplates){const coreFields=template.fields.filter(field=>!field.advanced);assert.ok(coreFields.length>=2,`${template.id} should have a useful core`);assert.ok(coreFields.length<=5,`${template.id} core should remain quick to complete`);for(const field of template.fields.filter(item=>item.advanced))assert.equal(field.required,false,`${template.id}.${field.key} advanced fields must be optional`)}});

test("profile prompt defaults prefer specific teaching context",()=>{const profile={role:"specialist",gradeBands:["6-8","9-12"],subjects:["music","visual-arts"],specificTeachingArea:"  Beginning Band  ",aiLevel:"sometimes",interests:["lesson-planning"],updatedAt:"2026-08-24T00:00:00.000Z"};assert.equal(profileGradeLabel(profile),"Grades 6–8, Grades 9–12");assert.equal(profileSubjectLabel(profile),"Beginning Band");assert.deepEqual(getProfilePromptDefaults(profile),{gradeLevel:"Grades 6–8, Grades 9–12",subject:"Beginning Band"});assert.deepEqual(getProfilePromptDefaults(null),{gradeLevel:"",subject:""})});

test("select fields preserve profile-prefilled values outside their standard options",()=>{const gradeField=promptTemplates[0].fields.find(field=>field.key==="gradeLevel");assert.ok(gradeField);const combined="Grades 6–8, Grades 9–12";const options=getPromptFieldOptions(gradeField,combined);assert.equal(options[0],combined);assert.equal(options.filter(option=>option===combined).length,1);assert.deepEqual(getPromptFieldOptions(gradeField,"Grades 6–8"),gradeField.options)});
