import type { Metadata } from "next";
import Link from "next/link";
import { CautionBox } from "@/components/content/CautionBox";
import { PageIntro,PageShell } from "@/components/ui/PageShell";
import { classroomUseCategories,studentAiSections } from "@/content/students-ai/guide";
import { pageMetadata } from "@/lib/pageMetadata";

export const metadata:Metadata=pageMetadata("Students + AI","Learning-goal-centered guidance for responsible, age-appropriate student AI use, disclosure, verification, and local policy.");

export default function StudentsAIPage(){return <PageShell>
  <PageIntro eyebrow="Educator Guidance · Students + AI" title="Build responsible practice around the learning goal" description="Help students understand when AI supports learning, when it bypasses learning, and how privacy, verification, disclosure, and local policy shape responsible use."/>
  <section className="section-shell student-frame"><span className="content-label">Start every decision here</span><blockquote>“What student thinking or performance is this assignment intended to demonstrate?”</blockquote><p>Then decide whether, where, and how AI assistance fits that evidence.</p></section>
  <section className="section-shell category-section"><div className="section-heading"><div><p className="eyebrow">A planning vocabulary</p><h2>Four possible classroom-use categories</h2></div><p>These are discussion and assignment-design categories—not universal policies. Local school, district, state, and organizational requirements govern actual use.</p></div><div className="category-grid">{classroomUseCategories.map((item,index)=><article key={item.title}><span aria-hidden="true">0{index+1}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
  <section className="section-shell student-guide"><div className="section-heading"><div><p className="eyebrow">The initial guide</p><h2>Eight decisions to make visible</h2></div></div>{studentAiSections.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.body}</p><div><strong>Ask:</strong> {item.question}</div></article>)}</section>
  <section className="section-shell decision-framework"><div><p className="eyebrow">A practical sequence</p><h2>Teacher decision framework</h2></div><ol><li><strong>Name the evidence.</strong><span>What should students know, decide, create, explain, or perform?</span></li><li><strong>Locate possible assistance.</strong><span>Where could AI support practice without replacing that evidence?</span></li><li><strong>Check conditions.</strong><span>Consider age, developmental readiness, privacy, access, bias, copyright, safety, and local policy.</span></li><li><strong>Make process visible.</strong><span>Choose disclosure, checkpoints, conversation, drafts, or performance evidence that fits.</span></li><li><strong>Communicate clearly.</strong><span>Give examples of permitted and non-permitted use before work begins.</span></li></ol></section>
  <section className="section-shell caution-section"><CautionBox title="Privacy and policy still govern"><p>Never ask students to enter names, IDs, identifiable grades, medical information, IEP or 504 documents, disciplinary records, or other personally identifiable information into a public AI system. Use only institutionally approved tools and follow local policy.</p></CautionBox><div className="next-step"><div><p className="content-label">Ready to revisit a task?</p><h2>Redesign an assignment around the evidence of learning.</h2></div><Link className="button button--primary" href="/prompt-builder/assignment-redesign">Open Assignment Redesign</Link></div></section>
</PageShell>}
