import { promptTemplateMap } from "../data/promptTemplates.ts"; import type { DifferentiateActivityInput,PromptWorkflowId } from "@/types/prompt";
const clean=(value:string|undefined,fallback:string)=>value?.trim()||fallback;
const sharedBoundary="Do not assume or invent details about individual students. Do not request or include student names, student IDs, identifiable grades, medical data, IEP or 504 documents, disciplinary records, or other personally identifiable information. Flag recommendations that require professional, legal, safety, accessibility, copyright, policy, or district-specific judgment.";

export function generateDifferentiateActivityPrompt(input:DifferentiateActivityInput){const grade=clean(input.gradeLevel,"K-12");const subject=clean(input.subject,"educator");return `Act as an experienced ${grade} ${subject} educator.\n\nI am teaching ${clean(input.activity,"a learning activity")}.\n\nMy primary learning objective is:\n${clean(input.objective,"Support the stated learning objective.")}\n\nContext:\n- Students/class size: ${clean(input.classSize,"Not specified")}\n- Time: ${clean(input.time,"Not specified")}\n- Resources: ${clean(input.resources,"Not specified")}\n- Relevant constraints: ${clean(input.constraints,"None provided")}\n\nI want help differentiating this learning experience for:\n${clean(input.differentiationNeed,"a range of learner needs")}\n\nSuggest practical modifications while preserving the primary learning objective rather than simply making the activity easier.\n\nFor each suggestion, explain:\n1. Who or what need it may support\n2. What changes\n3. What should remain consistent\n4. What I can observe to determine whether it is working\n\nDo not assume details about individual students that I have not provided.\n\nFlag recommendations that require professional, medical, IEP, 504, legal, safety, or district-specific judgment.`;}

const directions:Record<Exclude<PromptWorkflowId,"differentiate-activity">,string>={
 "lesson-planning":"Create a coherent lesson or rehearsal plan. For each phase, give the purpose, educator actions, student actions, approximate time, resources, and a formative check. Explain how the sequence builds toward the objective and evidence of learning. Include one realistic adjustment if time runs short.",
 "assessment-creation":"Draft the requested assessment and answer or scoring guidance. Label the learning evidence each item is intended to reveal. Include a mix appropriate to the target, then audit the draft for ambiguity, unintended reading load, multiple defensible answers, bias, and weak alignment.",
 "rubric-creation":"Create an analytic rubric with the requested performance levels. Use observable, parallel, asset-based descriptors for each criterion. Distinguish adjacent levels clearly, avoid vague frequency words when possible, and identify any criterion that risks measuring polish or compliance rather than the objective.",
 feedback:"Create a feedback approach that recognizes the described strength, focuses on the highest-leverage growth need, and leaves the intellectual or creative work with the student. Provide questions, concise feedback language, and a specific next-step opportunity. Do not write the student’s revision or infer personal traits.",
 "family-communication":"Draft a clear family-facing message with a useful subject line, short headings where helpful, the essential details, and a welcoming next step. Use the requested tone and access considerations. Leave explicit placeholders for any missing approved dates or contact details; do not invent them.",
 "activity-brainstorming":"Suggest distinct, discipline-authentic activity possibilities aligned to the goal. For each, explain the student work, educator role, materials and setup, approximate timing, evidence of learning, and one access consideration. Avoid superficial theme changes that do not alter the learning experience.",
 "assignment-redesign":"Redesign the assignment around the intended student thinking or performance. Show what should remain, what should change, which process evidence or checkpoints to add, and where AI could be encouraged, permitted with disclosure, restricted, or not appropriate for this particular goal. Include an equitable non-AI route and do not rely on AI detection.",
};

export function generateWorkflowPrompt(id:PromptWorkflowId,values:Record<string,string>){if(id==="differentiate-activity")return generateDifferentiateActivityPrompt(values as DifferentiateActivityInput);const template=promptTemplateMap[id];const grade=clean(values.gradeLevel,"K-12");const subject=clean(values.subject,clean(values.educatorRole,"educator"));const context=template.fields.filter(item=>item.key!=="gradeLevel"&&item.key!=="subject"&&item.key!=="educatorRole").map(item=>`- ${item.label}: ${clean(values[item.key],item.required===false?"None provided":"Not specified")}`).join("\n");return `Act as an experienced ${grade} ${subject}.\n\nTask: ${template.title}\n\nContext:\n${context}\n\n${directions[id]}\n\nOrganize the response so I can review and adapt it efficiently. State important assumptions and uncertainties instead of filling gaps with invented details.\n\n${sharedBoundary}\n\nAI should support educator judgment, not replace it.`;}
