export type CatchUpTopic={title:string;means:string;care:string;example:string;think:string};
export const twentyMinuteTopics:CatchUpTopic[]=[
 {title:"How generative AI produces responses",means:"A generative system predicts and assembles likely patterns from what it learned during training and from the current conversation. It does not retrieve a guaranteed correct answer or understand a class as an educator does.",care:"Plausible language can make pattern prediction look like knowledge. The output still needs review for accuracy, context, and instructional value.",example:"Asked for a science explanation, a system may combine common explanatory patterns into a fluent paragraph—even when one causal detail is wrong.",think:"Which parts of this output can I verify from disciplinary knowledge or reliable sources?"},
 {title:"Prompts and context",means:"A prompt is the instruction and context supplied to a system. Specific goals, audience, constraints, source material, output structure, and boundaries usually produce more useful results.",care:"A vague prompt invites generic assumptions. Better context can improve relevance, but private student information should never be the price of specificity.",example:"“Make a lesson” is less useful than naming the grade, objective, time, materials, prior learning, and evidence of understanding.",think:"What non-identifying context would help—and what information should stay out?"},
 {title:"Multimodal AI",means:"Some systems can work across text, images, audio, video, or documents. They may describe, transform, compare, or generate more than one kind of media.",care:"New input types create new learning possibilities and new privacy, consent, copyright, accessibility, and accuracy questions.",example:"A teacher might ask for a description of a public-domain image or a transcript summary, then check whether important visual or vocal details were missed.",think:"Do I have permission to share this media, and can I evaluate what the system overlooks?"},
 {title:"Reasoning capabilities",means:"Some systems can break a problem into steps, compare options, use tools, or produce an explanation that resembles reasoning. Performance varies by problem and presentation.",care:"A convincing chain of steps may still contain an invalid assumption, hidden shortcut, calculation error, or fabricated evidence.",example:"A system can outline several solution strategies for a math problem but mishandle a constraint in one strategy.",think:"What independent evidence shows the steps—not just the final wording—are sound?"},
 {title:"AI agents",means:"An AI agent is a system designed to pursue a goal through multiple steps, sometimes using tools or acting on information with less moment-to-moment direction.",care:"More autonomy can save effort but increases the need for narrow permissions, checkpoints, reliable data, and clear human responsibility.",example:"Conceptually, an agent might collect public resources and organize them into a draft unit map; an educator still verifies sources and decides what belongs.",think:"What could this system do, what should require approval, and who is accountable?"},
 {title:"Hallucinations",means:"AI can generate false facts, sources, quotations, calculations, policies, or details that sound completely confident. These errors are often called hallucinations.",care:"Fluent is not the same as accurate. Fabricated details can damage learning, trust, safety, and professional decisions.",example:"A system may invent a journal article, misquote a novel, or cite a district policy that does not exist.",think:"Which claims require a primary or authoritative source before I use them?"},
 {title:"Bias",means:"Outputs can reproduce or amplify patterns of bias in training data, product design, prompts, and human interpretation. Bias may appear through stereotypes, omissions, framing, or unequal performance.",care:"Classroom materials help shape whose experiences are visible and how students understand people, disciplines, and possibility.",example:"A list of “important inventors” may overrepresent familiar groups or describe cultures as uniform and static.",think:"Who is centered, missing, simplified, or described through a deficit lens?"},
 {title:"Privacy",means:"Information entered into an AI system may be stored, reviewed, retained, or used according to that system’s terms and institutional agreement.",care:"Educators have professional and legal responsibilities for student information. Removing a name may not fully de-identify a detailed story.",example:"Instead of pasting a student record, describe a general need: “learners who benefit from shorter directions and visual sequencing.”",
 think:"Could this combination of details identify a student, family, or colleague?"},
 {title:"Copyright",means:"Copyright questions can involve training data, inputs, generated output, substantial similarity, licenses, attribution, and the amount of human authorship. Rules and interpretations continue to develop.",care:"Educators and students need to distinguish access from permission and generated content from automatically risk-free content.",example:"Uploading a full copyrighted workbook or score is different from describing a learning objective and asking for an original activity structure.",think:"Do I have the right to provide this material, and what attribution or license does the final use require?"},
 {title:"Verification",means:"Verification means checking claims, citations, calculations, translations, examples, and recommendations against reliable evidence and professional knowledge.",care:"AI output can be a useful lead or draft, but it is not evidence merely because it is detailed or confident.",example:"A teacher checks a generated historical claim against primary sources and a trusted reference before putting it on a handout.",think:"What is the fastest reliable way to check the highest-risk part of this result?"},
 {title:"Limitations of AI detection",means:"AI-detection tools estimate patterns; they do not observe how a text was created and can produce false positives and false negatives.",care:"A score is not proof of authorship or misconduct. High-stakes accusations require fair process, context, policy, and stronger evidence.",example:"Formulaic or multilingual student writing may be flagged even when written without generative AI.",think:"What direct evidence of process and learning can I gather instead of relying on a detector?"},
 {title:"Responsible student use",means:"Responsible use connects AI choices to the learning goal, appropriate permission, privacy, verification, disclosure, and the student thinking that must remain visible.",care:"A universal rule rarely fits every age, task, discipline, or stage of learning. Clear expectations help students make defensible choices.",example:"AI might be permitted for brainstorming with disclosure but restricted during an independent writing sample intended to show current proficiency.",think:"What may the tool support, and what must the student demonstrate personally?"},
 {title:"Assessment implications",means:"AI makes some products easier to generate, so assessment may need stronger evidence of process, reasoning, conversation, revision, performance, or application.",care:"The goal is not to make every task AI-proof. It is to collect trustworthy evidence of the knowledge or performance that matters.",example:"A research assignment adds source notes, an in-class conference, revision decisions, and a short oral defense of the final claim.",think:"What student thinking or performance is this assignment intended to demonstrate?"},
 {title:"Human judgment",means:"Human judgment supplies purpose, relationships, ethics, context, accountability, and professional knowledge that an AI output cannot assume.",care:"Educators remain responsible for what is taught, how students are treated, whether materials are safe and appropriate, and how decisions are made.",example:"AI can propose accessibility options; the educator collaborates with the learner and appropriate professionals to decide what fits.",think:"Which parts of this decision should never be delegated?"},
];
