export const studentAiSections=[
 {title:"1. What students should understand about AI",body:"Students should know that generative AI predicts plausible content, can be confidently wrong, reflects patterns and bias in data, and does not know their classroom purpose. They need age-appropriate understanding of privacy, verification, authorship, disclosure, and the difference between assistance and evidence of their own learning.",question:"Can students explain both a useful capability and a meaningful limitation?"},
 {title:"2. When AI may support learning",body:"AI may support brainstorming, practice, feedback, explanation comparison, question generation, accessibility, or revision when those supports leave the intended thinking and performance with the student. Permission should be specific to the task and stage of work.",question:"Does the tool help students practice or notice something they still have to understand and demonstrate?"},
 {title:"3. When AI may bypass learning",body:"AI bypasses learning when it performs the interpretation, composition, calculation, translation, artistic choice, performance, source evaluation, or explanation the assignment is meant to reveal. A polished product can hide missing understanding.",question:"If AI completed this step, what evidence of learning would disappear?"},
 {title:"4. Academic integrity",body:"Academic integrity involves truthful representation of contribution, permitted assistance, attribution, and responsibility for submitted work. Expectations should be taught and connected to the learning purpose—not left as a vague warning. AI-detector scores are not proof of misconduct.",question:"Have students been shown what permitted help and honest disclosure look like for this exact task?"},
 {title:"5. Assignment design",body:"Assignments can gather stronger evidence through checkpoints, source notes, drafts, conferences, demonstrations, in-class application, reflection, revision decisions, and authentic audiences. The goal is better evidence of learning, not making every task impossible to complete with AI.",question:"Where can process, reasoning, or performance become visible without creating unnecessary workload?"},
 {title:"6. Verification",body:"Students should check factual claims, citations, calculations, translations, quotations, cultural context, and recommendations with reliable evidence. Verification is a disciplinary practice: checking a proof differs from corroborating a historical claim or evaluating a musical translation.",question:"Which claim has the highest consequence if it is wrong, and what source can verify it?"},
 {title:"7. Disclosure and transparency",body:"A useful disclosure can name the system or support used, the stage of work, what it contributed, what the student changed, and how claims were checked. The level of detail should fit student age, task, discipline, and local requirements.",question:"Could a reader understand the student’s contribution and evaluate the remaining evidence of learning?"},
 {title:"8. Teacher decision framework",body:"Begin with the intended learning evidence, consider age and independence, identify privacy and access risks, decide where assistance fits, name required process evidence, and communicate expectations before students begin. Revisit the decision when the task or tools change.",question:"Is the expectation understandable, equitable, enforceable, and aligned with local policy?"},
];
export const classroomUseCategories=[
 {title:"AI Encouraged",body:"The task intentionally develops AI literacy or benefits from comparing, critiquing, or directing AI output. Students still verify, disclose, and demonstrate the targeted learning."},
 {title:"AI Permitted with Disclosure",body:"Students may use specified forms of assistance at specified stages and explain how they used them. The remaining work still provides trustworthy evidence."},
 {title:"AI Restricted",body:"Some assistance may be allowed, but particular stages, tools, or outputs are limited because they would obscure important learning evidence."},
 {title:"AI Not Appropriate for This Learning Goal",body:"The task requires independent or live performance that AI assistance would replace—for example, an on-demand writing sample, spontaneous conversation, or individual skill demonstration."},
];
